cc_library(
    name = "nugget_tools",
    srcs = [
        "nugget_tools.cc",
    ],
    hdrs = [
        "nugget_tools.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@com_github_gflags_gflags//:gflags",
        "@nugget_host_linux_citadel_libnos//:libnos",
    ],
)
